apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: k8s-headlamp
  namespace: headlamp
spec:
  syncConfig:
    resyncInterval: 60s
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "homescale"
        envSlug: "prod"
        secretsPath: "/k8s/headlamp"
      credentialsRef:
        secretName: infisical-operator-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: oidc # pragma: allowlist secret
      secretNamespace: headlamp
      creationPolicy: Owner
      secretType: Opaque
      template:
        includeAllSecrets: true
        metadata: {} # blocks copying ArgoCD's tracking-id annotation, which otherwise gets this secret pruned every sync
