apiVersion: v1
kind: Service
metadata:
  name: headlamp-tailscale
  namespace: headlamp
  annotations:
    tailscale.com/tags: "tag:k8s,tag:app-headlamp,tag:cluster-{{ required "cluster.name is required" .Values.cluster.name }}"
    tailscale.com/hostname: "headlamp-{{ required "cluster.name is required" .Values.cluster.name }}"
    tailscale.com/proxy-group: ingress
    external-dns.alpha.kubernetes.io/hostname: "headlamp.{{ required "cluster.name is required" .Values.cluster.name }}REDACTED"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/instance: headlamp
  ports:
    - name: http
      port: 80
      targetPort: http
