{{- $tailnet := .Values.tailscale.tailnet }}
{{- $cluster := required "cluster.name is required" .Values.cluster.name }}
{{- range .Values.tailscale.egressClusters }}
---
apiVersion: v1
kind: Service
metadata:
  name: headlamp-{{ $cluster }}-egress-{{ . }}
  namespace: headlamp
  annotations:
    tailscale.com/tailnet-fqdn: "k8s-api-{{ . }}.{{ $tailnet }}"
    tailscale.com/tags: "tag:k8s,tag:app-headlamp,tag:cluster-{{ $cluster }}"
    tailscale.com/hostname: "headlamp-{{ $cluster }}-egress-{{ . }}"
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - port: 443
{{- end }}
