{{- $tailnet := .Values.tailscale.tailnet }}
{{- range .Values.tailscale.egressClusters }}
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-api-{{ . }}
  namespace: headlamp
  annotations:
    tailscale.com/tailnet-fqdn: "k8s-api-{{ . }}.{{ $tailnet }}"
    tailscale.com/proxy-group: egress
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - port: 443
{{- end }}
