kind: Cluster
name: manor
labels:
  REDACTED/name: manor
  REDACTED/region: boa
  REDACTED/zone: manor
  REDACTED/platform: metal
  region: boa
talos:
  version: v1.10.5
kubernetes:
  version: v1.33.2
features:
  enableWorkloadProxy: true
  useEmbeddedDiscoveryService: true
  backupConfiguration:
    interval: 1h
patches:
  - name: nodeLabels
    inline:
      machine:
        nodeLabels:
          REDACTED/name: manor
          REDACTED/region: boa
          REDACTED/zone: manor
          REDACTED/platform: metal
  - file: ./patches/global-patch.yaml
  - file: ./patches/allow-schedule-control-plane-patch.yaml
---
kind: ControlPlane
machineClass:
  name: manor
  size: 3
---
kind: Workers
machineClass:
  name: manor
  size: unlimited