{{- $region := required "provider.region is required" .Values.provider.region -}}
{{- $platform := required "provider.platform is required" .Values.provider.platform -}}
{{- $image := required (printf "unsupported platform: %s" $platform) (get .Values.provider.images $platform) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      {{- with .Values.provider.address }}
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{"name":{{ printf "%s-mgmt" $region | quote }},"namespace":{{ $.Release.Namespace | quote }},"ips":[{{ . | quote }}]}]'
      {{- end }}
    spec:
      containers:
        - name: omni-infra-provider
          image: {{ $image | quote }}
          imagePullPolicy: IfNotPresent
          args:
            - --omni-api-endpoint={{ .Values.omni.apiEndpoint }}
            - --id={{ $region }}-{{ $platform }}
            - --machine-labels=region={{ $region }},platform={{ $platform }}
            - --provider-name={{ $region }}-{{ $platform }}
            {{- if and (eq $platform "metal") (not (eq false .Values.provider.secureBootEnabled)) }}
            - --secure-boot-enabled
            {{- end }}
            - --api-advertise-address={{ required "provider.address is required" .Values.provider.address | splitList "/" | first }}
          env:
            - name: OMNI_SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: omni-infra-provider
                  key: {{ $region }}-{{ $platform }} # pragma: allowlist secret
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
