{{- $region := required "provider.region is required" .Values.provider.region -}}
{{- $platform := required "provider.platform is required" .Values.provider.platform -}}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: k8s-omni-infra-provider
  namespace: omni-infra-provider
spec:
  syncConfig:
    resyncInterval: 60s
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "homescale"
        envSlug: "prod"
        secretsPath: "/k8s/omni/infra-providers"
      credentialsRef:
        secretName: infisical-operator-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: omni-infra-provider # pragma: allowlist secret
      secretNamespace: omni-infra-provider
      creationPolicy: Owner
      secretType: Opaque
