path: apps/homepage
namespace: homepage
releaseName: homepage
syncWave: 0
podSecurity: privileged
values:
  image:
    repository: ghcr.io/homescalecloud/homepage
    tag: "latest"  # pragma: allowlist secret
exposePublic:
  cluster: boa1-prod
  fqdn: xxx
  port: 80

defaultDeploy: false
