path: apps/homepage
namespace: homepage
releaseName: homepage
syncWave: 0
podSecurity: privileged
annotations:
  argocd-image-updater.argoproj.io/image-list: "img=ghcr.io/homescalecloud/homepage"
  argocd-image-updater.argoproj.io/img.update-strategy: newest-build
  argocd-image-updater.argoproj.io/img.allow-tags: "regexp:^[0-9a-f]{40}$"
  argocd-image-updater.argoproj.io/img.helm.image-tag: image.tag
values:
  image:
    repository: ghcr.io/homescalecloud/homepage
    tag: "latest"  # pragma: allowlist secret
exposePublic:
  cluster: boa1-prod
  fqdn: REDACTED
  port: 80

defaultDeploy: false
clusters:
  boa1-prod:
    deploy: true
