LABEL org.opencontainers.image.source=https://github.com/MorrisLAN/morrislan
LABEL org.opencontainers.image.description Simple homepage for morrislan.net
FROM docker.io/library/nginx:alpine
COPY index.html /usr/share/nginx/html
