apiVersion: v2
name: ziti-controller-mgmt-2
description: Helm chart for deploying a second OpenZiti Controller (HA)
type: application
version: 0.1.0
dependencies:
  - name: ziti-controller
    version: 3.1.1
    repository: https://docs.openziti.io/helm-charts/
