path: apps/headlamp
namespace: headlamp
releaseName: headlamp
syncWave: 0
defaultDeploy: false
netbird:
  policy:
    rules:
      - sources: ["team-infra-plat", "team-sec-plat"]
        protocol: tcp
        ports: ["443"]
  cname:
    - fqdn: REDACTED
      cluster: mgmt
values:
  cluster:
    name: "{{ .Values.cluster.name }}"
  headlamp:
    replicaCount: 1
    service:
      port: 443
    config:
      inClusterContextName: "{{ .Values.cluster.name }}"
      tlsCertPath: /headlamp-tls/tls.crt
      tlsKeyPath: /headlamp-tls/tls.key
      oidc:
        secret:
          create: false
        externalSecret:
          enabled: true
          name: oidc
          hasScopes: true
    probes:
      scheme: HTTPS
    volumes:
      - name: headlamp-tls
        secret:
          secretName: headlamp-tls
    volumeMounts:
      - name: headlamp-tls
        mountPath: /headlamp-tls
        readOnly: true
    pluginsManager:
      enabled: true
      configContent: |
        plugins:
          - name: headlamp-argocd
            source: https://artifacthub.io/packages/headlamp/headlamp-argocd/headlamp-argocd
            version: 0.1.3
