apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-assistant-tls
  namespace: home-assistant
spec:
  secretName: home-assistant-tls
  issuerRef:
    name: {{ .Values.certIssuer | default "letsencrypt" }}
    kind: ClusterIssuer
  dnsNames:
    - ha.home-assistant.{{ required "cluster.name is required" .Values.cluster.name }}xxx
