apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.zigbee2mqtt.pvc.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mqtt.pvc.config.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mqtt.pvc.data.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.matter.pvc.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.homebridge.pvc.size }}
