apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.zigbee2mqtt.pvc.size }}
