{{- $pvcs := list "home-assistant" "zigbee2mqtt" "mqtt-config" "mqtt-data" "matter" "homebridge" -}}
{{- range $pvcs }}
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: k8s-volsync-{{ . }}
  namespace: home-assistant
spec:
  syncConfig:
    resyncInterval: 60s
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "homescale"
        envSlug: "prod"
        secretsPath: "/k8s/volsync"
      credentialsRef:
        secretName: infisical-operator-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: {{ . }}-volsync-repo # pragma: allowlist secret
      secretNamespace: home-assistant
      creationPolicy: Owner
      secretType: Opaque
      template:
        includeAllSecrets: true
        data:
          RESTIC_REPOSITORY: "{{`{{ .RESTIC_REPOSITORY.Value }}`}}/{{ $.Values.cluster.name }}/{{ . }}"
{{- end }}
