apiVersion: v1
kind: Service
metadata:
  name: ha
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: 8123
---
apiVersion: v1
kind: Service
metadata:
  name: z2m
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: mqtt-alt
      port: 1884
      targetPort: 1884
    - name: websocket
      port: 9001
      targetPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: matter
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 5580
      targetPort: 5580
---
apiVersion: v1
kind: Service
metadata:
  name: homebridge
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: 8581
