apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: homecraft
spec:
  networkRouterRef:
    name: '{{ required "cluster.name is required" .Values.cluster.name }}'
    namespace: netbird
  serviceRef:
    name: mc
  groups:
    - name: app-homecraft
    - name: cluster-{{ required "cluster.name is required" .Values.cluster.name }}
