apiVersion: v1
kind: Service
metadata:
  name: "mc"
  labels:
    REDACTED/name: "{{ .Release.Name }}"
  annotations:
    tailscale.com/tags: "tag:app-homecraft,tag:cluster-{{ required "cluster.name is required" .Values.cluster.name }}"
    tailscale.com/hostname: "mc-{{ required "cluster.name is required" .Values.cluster.name }}"
    external-dns.alpha.kubernetes.io/hostname: "homecraft.{{ required "cluster.name is required" .Values.cluster.name }}REDACTED"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
  - name: minecraft
    port: 25565
    targetPort: minecraft
    protocol: TCP
  selector:
    app: "{{ .Release.Name }}-minecraft"
