defaultNamespace: traefik
name: traefik-public
helm:
  releaseName: traefik-public
  chart: ./
  takeOwnership: true
  force: true
  values:
    traefik:
      deployment:
        replicas: 2
      service:
        type: LoadBalancer
      ingressClass:
        enabled: true
        name: traefik-public
        isDefaultClass: false
      providers:
        kubernetesIngress:
          enabled: true
          ingressClass: traefik-public
          labelSelector: traefik-instance=public
          publishedService:
            enabled: true
        kubernetesCRD:
          enabled: true
          ingressClass: traefik-public
          labelSelector: traefik-instance=public

overrideTargets:
  - clusterSelector:
      matchLabels:
        REDACTED/traefik-public: enabled
  - clusterSelector:
      matchLabels:
        REDACTED/env: mgmt
