defaultNamespace: traefik
name: traefik-public
helm:
  releaseName: traefik-public
  chart: ./
  takeOwnership: true
  force: true
  values:
    traefik:
      deployment:
        replicas: 2
      service:
        type: LoadBalancer
      ingressClass:
        enabled: true
        name: traefik-public
        isDefaultClass: false
      providers:
        kubernetesIngress:
          enabled: true
          ingressClass: traefik-public
          labelSelector: xxx/class=public
          publishedService:
            enabled: true
        kubernetesCRD:
          enabled: true
          ingressClass: traefik-public
          labelSelector: xxx/class=public
      additionalArguments:
        - "--providers.kubernetesingress.ingressclass=traefik-public"

overrideTargets:
  - clusterSelector:
      matchLabels:
        xxx/traefik-public: enabled
  - clusterSelector:
      matchLabels:
        xxx/env: mgmt
