extends: default
ignore: |
  apps/*/templates/**
  deploy/*/templates/**
rules:
  truthy: disable
  document-start: disable
  line-length:
    max: 251
    level: warning
  braces:
    forbid: false
    max-spaces-inside: 1
