extends: default
ignore: |
  apps/**/templates/**
  argocd/**/templates/**
  apps/netbird/crds/tcproutes.yaml
  apps/volsync/crds/crds.yaml
rules:
  truthy: disable
  document-start: disable
  line-length:
    max: 251
    level: warning
  braces:
    forbid: false
    max-spaces-inside: 1
