apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: metrics
spec:
  type: ClusterIP
  ports:
    - name: http-web
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: aggregator
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: metrics
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 3100
      protocol: TCP
      targetPort: http-metrics
    - name: grpc
      port: 9095
      protocol: TCP
      targetPort: grpc
  selector:
    app.kubernetes.io/name: loki
