path: apps/cert-manager
namespace: cert-manager
releaseName: cert-manager
syncWave: -30
defaultDeploy: true
values:
  cert-manager:
    crds:
      enabled: true
ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: cert-manager-webhook
    jsonPointers:
      - /webhooks
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: cert-manager-webhook
    jsonPointers:
      - /webhooks
