apiVersion: twingate.com/v1beta
kind: TwingateConnector
metadata:
  name: {{ .Values.global.cluster }}
spec:
  name: {{ .Values.global.cluster }}
  imagePolicy:
    provider: dockerhub
    schedule: "0 0 * * *"
