apiVersion: v1
kind: ConfigMap
metadata:
  name: multus-daemon-config
  namespace: kube-system
data:
  daemon-config.json: |
    {
      "cniConfigDir": "/host/etc/cni/net.d",
      "binDir": "/host/opt/cni/bin",
      "socketDir": "/host/run/multus/",
      "multusAutoconfigDir": "/host/etc/cni/net.d",
      "multusConfigFile": "auto",
      "logToStderr": true,
      "logLevel": "error"
    }
