apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: k8s-{{ .Values.cluster.name }}
spec:
  type: kube-apiserver
  replicas: 2
  tags: ["tag:k8s", "tag:cluster-{{ .Values.cluster.name }}", "tag:region-{{ .Values.cluster.region }}"]
  kubeAPIServer:
    mode: auth
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: ingress
spec:
  type: ingress
  replicas: 2
  tags: ["tag:app", "tag:cluster-{{ .Values.cluster.name }}", "tag:region-{{ .Values.cluster.region }}"]
  hostnamePrefix: {{ .Values.cluster.name }}
