{{- if eq .Values.cluster.name "boa1-prod" }}
apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: grafana
spec:
  networkRouterRef:
    name: {{ required "cluster.name is required" .Values.cluster.name | quote }}
    namespace: netbird
  serviceRef:
    name: metrics-grafana
  groups:
    - name: app-metrics
    - name: cluster-{{ required "cluster.name is required" .Values.cluster.name }}
{{- end }}
