{{- if eq .Values.cluster.name "boa1-prod" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-aggregator
  namespace: metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-aggregator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-kube-prometheus-st-prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus-aggregator
    namespace: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: aggregator
  namespace: metrics
spec:
  serviceAccountName: prometheus-aggregator
  replicas: 1
  retention: 30d
  enableRemoteWriteReceiver: true
  serviceMonitorSelector:
    matchLabels:
      prometheus: aggregator-only
  podMonitorSelector:
    matchLabels:
      prometheus: aggregator-only
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
{{- end }}
