{{- $tailnet := .Values.tailscale.tailnet }}
{{- $cluster := required "cluster.name is required" .Values.cluster.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-{{ $cluster }}-egress
  namespace: metrics
  annotations:
    tailscale.com/tailnet-fqdn: "prometheus-metrics-boa1-prod-aggr.{{ $tailnet }}"
    tailscale.com/tags: "tag:k8s,tag:app-metrics,tag:cluster-{{ $cluster }}"
    tailscale.com/hostname: "metrics-{{ $cluster }}-egress"
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - port: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-{{ $cluster }}-egress-loki
  namespace: metrics
  annotations:
    tailscale.com/tailnet-fqdn: "loki-metrics-boa1-prod.{{ $tailnet }}"
    tailscale.com/tags: "tag:k8s,tag:app-metrics,tag:cluster-{{ $cluster }}"
    tailscale.com/hostname: "metrics-{{ $cluster }}-egress-loki"
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - port: 3100
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-{{ $cluster }}-egress-alertmanager
  namespace: metrics
  annotations:
    tailscale.com/tailnet-fqdn: "alertmanager-metrics-boa1-prod.{{ $tailnet }}"
    tailscale.com/tags: "tag:k8s,tag:app-metrics,tag:cluster-{{ $cluster }}"
    tailscale.com/hostname: "metrics-{{ $cluster }}-egress-alertmanager"
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - port: 80
