apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-prod
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: git@github.com:HomeScaleCloud/homescale.git
      targetRevision: main
      path: clusters/prod
      directory:
        recurse: true
    - repoURL: git@github.com:HomeScaleCloud/homescale.git
      targetRevision: main
      path: apps/catalog
      helm:
        releaseName: apps-prod
        values: |
          cluster:
            name: prod
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
