cluster:
  apiServer:
    admissionControl:
      - name: PodSecurity
        configuration:
          apiVersion: pod-security.admission.config.k8s.io/v1beta1
          kind: AdmissionConfiguration
          exemptions:
            namespaces:
              - kube-system
              - argocd
              - netbird
              - rook-ceph
machine:
  nodeLabels:
    xxx/name: ${CLUSTER_NAME}
  network:
    interfaces:
      - interface: bond0
        dhcp: true
        bond:
          mode: 802.3ad
          lacpRate: fast
          xmitHashPolicy: layer3+4
          miimon: 100
          interfaces:
            - eno1
            - eno2
