apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: automatron-read-services
  namespace: omni
rules:
  - apiGroups: [""]
    resources:
      - services
    resourceNames:
      - api
      - k8s
    verbs: ["get"]
