apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: automatron-secrets
  namespace: {{ .Release.Namespace }}
spec:
  syncConfig:
    resyncInterval: 60s
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "homescale"
        envSlug: "prod"
        secretsPath: "/k8s/automatron"
      credentialsRef:
        secretName: infisical-operator-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: automatron-secrets # pragma: allowlist secret
      secretNamespace: {{ .Release.Namespace }}
      creationPolicy: Owner
      secretType: Opaque
      template:
        includeAllSecrets: true
        metadata: {}
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: automatron-infisical-operator-creds
  namespace: {{ .Release.Namespace }}
spec:
  syncConfig:
    resyncInterval: 60s
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "homescale"
        envSlug: "prod"
        secretsPath: "/k8s/infisical"
      credentialsRef:
        secretName: infisical-operator-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: automatron-infisical-operator-creds # pragma: allowlist secret
      secretNamespace: {{ .Release.Namespace }}
      creationPolicy: Owner
      secretType: Opaque
      template:
        includeAllSecrets: true
        metadata: {}
