path: apps/omni-infra-provider
namespace: omni-infra-provider
releaseName: omni-infra-provider
syncWave: 0
podSecurity: privileged
defaultDeploy: false
clusters:
  boa1-gw:
    deploy: true
    values:
      provider:
        platform: metal
        address: "10.1.245.100/24"
values:
  omni:
    apiEndpoint: "https://xxx"
  netbird:
    image: "ghcr.io/netbirdio/netbird:0.72.4"
    autoGroups:
      - "cluster-{{ .Values.cluster.name }}"
      - "app-omni-infra-provider"
  provider:
    region: "{{ .Values.cluster.region }}"
    platform: ""
    images:
      metal: "ghcr.io/siderolabs/omni-infra-provider-bare-metal:v0.10.1"
      virt: "ghcr.io/siderolabs/omni-infra-provider-kubevirt:v0.1.0"
