apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-mgmt
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: git@github.com:HomeScaleCloud/homescale.git
      targetRevision: main
      path: clusters/mgmt
      directory:
        recurse: true
        exclude: 'cluster.yaml'
    - repoURL: git@github.com:HomeScaleCloud/homescale.git
      targetRevision: main
      path: apps
      helm:
        releaseName: apps-mgmt
        values: |
          cluster:
            name: mgmt
          apps:
            cilium:
              deploy: false
            external-dns:
              deploy: true
            external-dns-crs:
              deploy: true
            multus:
              deploy: false
            netbird-crs:
              values:
                kubeApiServer: "https://kubernetes.default.svc/"
            node-inotify-limits:
              deploy: true
            omni:
              deploy: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /metadata/finalizers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
