{
 "title": "Longhorn Monitoring",
 "description": "An example dashboard for Longhorn. Updated by ONZACK AG (Robin Hermann)",
 "tags": [
  "Storage",
  "K8s",
  "Longhorn"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_info, cluster)"
    }
   },
   {
    "name": "volume",
    "label": "Volume",
    "query": {
     "query": "label_values(longhorn_volume_state{cluster=~\"$cluster\"},volume)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alert Timeline",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "max without (alertstate) ((ALERTS{cluster=~\"$cluster\", alertname=~\"Longhorn.*\", severity=\"critical\", alertstate=\"firing\"} * 2) or (ALERTS{cluster=~\"$cluster\", alertname=~\"Longhorn.*\", alertstate=\"pending\"} * 1) or (ALERTS{cluster=~\"$cluster\", alertname=~\"Longhorn.*\", severity=\"warning\"} * 1))",
       "legendFormat": "{{alertname}} [{{severity}}]"
      }
     ]
    },
    {
     "title": "Active Alerts",
     "type": "table",
     "description": "Empty until Longhorn-specific PrometheusRules are added (see https://longhorn.io/docs/1.3.1/monitoring/alert-rules-example/).",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "ALERTS{cluster=~\"$cluster\", alertname=~\"Longhorn.*\", alertstate=~\"firing|pending\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Longhorn Manager Pod Logs",
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "{cluster=~\"$cluster\", namespace=\"longhorn-system\", pod=~\"longhorn-manager-.*\"}"
      }
     ]
    }
   ]
  },
  { "title": "Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Total Number Of Volumes",
   "type": "stat",
   "description": "The total number of volumes in the Longhorn storage system",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(longhorn_volume_capacity_bytes{volume=~\"$volume\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Number Of Healthy Volumes",
   "type": "stat",
   "description": "Healthy volumes are volumes that are attaching to a node and have the number of healthy replicas equals to the expected number of replicas.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\r\n  (longhorn_volume_robustness{volume=~\"$volume\"} == 1)\r\n  or\r\n  (longhorn_volume_robustness{volume=~\"$volume\", robustness=\"healthy\"} == 1)\r\n) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Volume Actual Size",
   "type": "timeseries",
   "description": "Note that Longhorn volume actual size is not the size of the filesystem inside a Longhorn volume.  See more at : https://longhorn.io/docs/1.0.2/volumes-and-nodes/volume-size/#volume-actual-size",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( (avg by (volume) (longhorn_volume_actual_size_bytes{volume=~\"$volume\"}))/ (avg by (volume) (longhorn_volume_capacity_bytes{volume=~\"$volume\"})) ) *100"
    }
   ]
  },
  {
   "title": "Number Of Degraded Volumes",
   "type": "stat",
   "description": "Degraded volumes are volumes that have the number of healthy replicas smaller than the expected number of replicas. e.g. User creates a volume with 2 replicas but 1 replicas is failed.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\r\n  (longhorn_volume_robustness{volume=~\"$volume\"} == 2)\r\n  or\r\n  (longhorn_volume_robustness{volume=~\"$volume\", robustness=\"degraded\"} == 1)\r\n) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Number Of Fault Volumes",
   "type": "stat",
   "description": "Fault volumes are volumes that doesn't have any healthy replica.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\r\n  (longhorn_volume_robustness{volume=~\"$volume\"} == 3)\r\n  or\r\n  (longhorn_volume_robustness{volume=~\"$volume\", robustness=\"faulted\"} == 1)\r\n) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Volume Capacity",
   "type": "table",
   "description": "The capacity of each Longhorn volume",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (pvc_namespace, pvc, volume) (longhorn_volume_capacity_bytes{volume=~\"$volume\"})",
     "legendFormat": "{{volume}}"
    },
    {
     "expr": "label_replace(label_replace(avg by(volume, namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"}),\"pvc\",\"$1\",\"persistentvolumeclaim\",\"(.*)\"),\"pvc_namespace\",\"$1\",\"namespace\",\"(.*)\")",
     "legendFormat": "{{volume}}"
    },
    {
     "expr": "100 *\r\n  label_replace(\r\n    avg by (volume, namespace, persistentvolumeclaim) (kubelet_volume_stats_used_bytes),\r\n    \"pvc\", \"$1\", \"persistentvolumeclaim\", \"(.*)\"\r\n  )\r\n/ on (namespace, pvc)\r\n  (\r\n    label_replace(\r\n      avg by (pvc_namespace, pvc, volume) (longhorn_volume_capacity_bytes{volume=~\"$volume\"}),\r\n      \"namespace\", \"$1\", \"pvc_namespace\", \"(.*)\"\r\n    )\r\n    and on (volume)\r\n      (\r\n        (longhorn_volume_state != 3)\r\n        or\r\n        (longhorn_volume_state{state!=\"detached\"} == 1)\r\n      )\r\n  )",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Number Of Attached Volumes",
   "type": "stat",
   "description": "Attached volumes are volumes that are currently attaching to a node",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\r\n  (longhorn_volume_state{volume=~\"$volume\"} == 2)\r\n  or\r\n  (longhorn_volume_state{volume=~\"$volume\", state=\"attached\"} == 1)\r\n) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Number Of Detached Volumes",
   "type": "stat",
   "description": "Detached volumes are volumes that aren't currently attaching to a node",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\r\n  (longhorn_volume_state{volume=~\"$volume\"} == 3)\r\n  or\r\n  (longhorn_volume_state{volume=~\"$volume\", state=\"detached\"} == 1)\r\n) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Number Of Nodes",
     "type": "stat",
     "description": "The total number of nodes in the Longhorn storage system",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(longhorn_node_count_total{cluster=~\"$cluster\"}) OR on() vector(0)"
      }
     ]
    },
    {
     "title": "Number Of Disabled Nodes",
     "type": "stat",
     "description": "Disabled nodes are nodes that are disabled by the user.  When users disable a node, Longhorn will not use the node's storage for replica scheduling. Note that Longhorn can still attach a volume to disabled nodes because the actual data of the volume could be on a different node.",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(longhorn_node_status{cluster=~\"$cluster\", condition=\"allowScheduling\"}==0) OR on() vector(0)"
      }
     ]
    },
    {
     "title": "Node Storage Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(longhorn_node_storage_usage_bytes{cluster=~\"$cluster\"}/longhorn_node_storage_capacity_bytes{cluster=~\"$cluster\"}) * 100"
      }
     ]
    },
    {
     "title": "Number Of Schedulable Nodes",
     "type": "stat",
     "description": "Schedulable nodes are nodes that Longhorn can use their storage for replica scheduling.",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(count(longhorn_node_status{cluster=~\"$cluster\", condition=\"schedulable\"}==1) OR on() vector(0)) - (count(longhorn_node_status{cluster=~\"$cluster\", condition=\"allowScheduling\"}==0) OR on() vector(0))"
      }
     ]
    },
    {
     "title": "Number Of Failed Nodes",
     "type": "stat",
     "description": "Failed Nodes are nodes that Longhorn cannot attach volumes to and cannot schedule replicas onto. e.g: when the nodes went down.",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(avg(longhorn_node_count_total{cluster=~\"$cluster\"}) OR on() vector(0)) - (count(longhorn_node_status{condition=\"ready\"}==1) OR on() vector(0))"
      }
     ]
    },
    {
     "title": "Node Capacity",
     "type": "table",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "longhorn_node_storage_capacity_bytes{cluster=~\"$cluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Number of Volumes Per Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (node) (\r\n  (longhorn_volume_state{cluster=~\"$cluster\"} == 2)\r\n  or\r\n  (longhorn_volume_state{cluster=~\"$cluster\", state=\"attached\"} == 1)\r\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space Usage",
     "type": "timeseries",
     "description": "The capacity of each Longhorn volume",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(longhorn_disk_usage_bytes{cluster=~\"$cluster\"}/longhorn_disk_capacity_bytes{cluster=~\"$cluster\"})*100"
      }
     ]
    },
    {
     "title": "Disk Capacity",
     "type": "table",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "longhorn_disk_capacity_bytes{cluster=~\"$cluster\"}",
       "legendFormat": "{{disk}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU & Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(longhorn_node_cpu_usage_millicpu{cluster=~\"$cluster\"} / longhorn_node_cpu_capacity_millicpu{cluster=~\"$cluster\"}) * 100"
      }
     ]
    },
    {
     "title": "Node Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "( longhorn_node_memory_usage_bytes{cluster=~\"$cluster\"} / longhorn_node_memory_capacity_bytes{cluster=~\"$cluster\"} ) * 100"
      }
     ]
    },
    {
     "title": "Instance Manager CPU Usage",
     "type": "timeseries",
     "description": "Instance managers are pods that contains the engine and replica processes of Longhorn volumes. See more at https://longhorn.io/docs/1.0.2/concepts/#11-the-longhorn-manager-and-the-longhorn-engine ",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "milicpu" } },
     "targets": [
      {
       "expr": "longhorn_instance_manager_cpu_usage_millicpu{cluster=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Instance Manager CPU Used from Request",
     "type": "timeseries",
     "description": "Instance managers are pods that contains the engine and replica processes of Longhorn volumes. See more at https://longhorn.io/docs/1.0.2/concepts/#11-the-longhorn-manager-and-the-longhorn-engine ",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(longhorn_instance_manager_cpu_usage_millicpu{cluster=~\"$cluster\"}/longhorn_instance_manager_cpu_requests_millicpu{cluster=~\"$cluster\"})*100"
      }
     ]
    },
    {
     "title": "Instance Manager Memory Usage",
     "type": "timeseries",
     "description": "Instance managers are pods that contains the engine and replica processes of Longhorn volumes. See more at https://longhorn.io/docs/1.0.2/concepts/#11-the-longhorn-manager-and-the-longhorn-engine ",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "longhorn_instance_manager_memory_usage_bytes{cluster=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Longhorn Manager CPU Usage",
     "type": "timeseries",
     "description": "Longhorn manager pods manage the control plane of the Longhorn system. e.g. Volume scheduling, attaching, detaching, backup, etc,..",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "milicpu" } },
     "targets": [
      {
       "expr": "longhorn_manager_cpu_usage_millicpu{cluster=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Longhorn Manager Memory Usage",
     "type": "timeseries",
     "description": "Longhorn manager pods manage the control plane of the Longhorn system. e.g. Volume scheduling, attaching, detaching, backup, etc,..",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "longhorn_manager_memory_usage_bytes{cluster=~\"$cluster\"}"
      }
     ]
    }
   ]
  }
 ]
}