apiVersion: twingate.com/v1beta
kind: TwingateResource
metadata:
  name: rancher
spec:
  name: Rancher
  address: traefik.traefik.svc.cluster.local
  alias: mgmt.homescale.cloud
  securityPolicyId: U2VjdXJpdHlQb2xpY3k6MTA3MDUwOA==
  isBrowserShortcutEnabled: true
---
apiVersion: twingate.com/v1beta
kind: TwingateResourceAccess
metadata:
  name: rancher-team-infra-plat
spec:
  resourceRef:
    name: rancher
    namespace: {{ .Release.Namespace }}
  principalExternalRef:
    type: group
    name: team-infra-plat
---
apiVersion: twingate.com/v1beta
kind: TwingateResourceAccess
metadata:
  name: rancher-team-sec-plat
spec:
  resourceRef:
    name: rancher
    namespace: {{ .Release.Namespace }}
  principalExternalRef:
    type: group
    name: team-sec-plat
---
apiVersion: twingate.com/v1beta
kind: TwingateResourceAccess
metadata:
  name: rancher-github-actions
spec:
  resourceRef:
    name: rancher
    namespace: {{ .Release.Namespace }}
  principalExternalRef:
    type: serviceAccount
    name: GitHub Actions
