path: apps/tailscale
namespace: tailscale
releaseName: tailscale
syncWave: -20
podSecurity: privileged
syncOptions:
  - ServerSideApply=true
defaultDeploy: true
values:
  cluster:
    name: '{{ .Values.cluster.name }}'
  tailscale-operator:
    installCRDs: true
    operatorConfig:
      hostname: 'ts-operator-{{ .Values.cluster.name }}'
      defaultTags:
        - 'tag:k8s'
    proxyConfig:
      defaultTags: 'tag:k8s,tag:cluster-{{ .Values.cluster.name }}'
      defaultProxyClass: default
