apiVersion: v2
name: tailscale
description: Helm chart for deploying Tailscale Operator
type: application
version: 0.1.0
dependencies:
  - name: tailscale-operator
    version: 1.94.1
    repository: https://pkgs.tailscale.com/helmcharts
