defaultDeploy: false

path: apps/rook-ceph
namespace: rook-ceph
podSecurity: privileged
syncWave: -5
values:
  rook-ceph:
    crds:
      enabled: true
    logLevel: INFO
    currentNamespaceOnly: false
    csi:
      provisionerReplicas: 1
      cephFSPlugin:
        resources:
          plugin:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 1Gi
          registrar:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              memory: 256Mi
          liveness:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              memory: 256Mi
      rbdPlugin:
        resources:
          plugin:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 1Gi
          registrar:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              memory: 256Mi
          liveness:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              memory: 256Mi
      provisioner:
        resources:
          provisioner:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 256Mi
          resizer:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 256Mi
          attacher:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 256Mi
          snapshotter:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 256Mi
          plugin:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 1Gi
          liveness:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              memory: 256Mi

clusters:
  prod:
    deploy: true
