apiVersion: v2
name: rook-ceph
description: Helm chart for deploying rook-ceph
type: application
version: 0.1.0
dependencies:
  - name: rook-ceph
    version: v1.19.0
    repository: https://charts.rook.io/release
  - name: rook-ceph-cluster
    version: v1.19.0
    repository: https://charts.rook.io/release
