apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: k8s-time-machine
  namespace: time-machine
spec:
  syncConfig:
    resyncInterval: 60s
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "homescale"
        envSlug: "prod"
        secretsPath: "/k8s/time-machine"
      credentialsRef:
        secretName: infisical-operator-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: time-machine
      secretNamespace: time-machine
      creationPolicy: Owner
      secretType: Opaque
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: k8s-volsync-time-machine
  namespace: time-machine
spec:
  syncConfig:
    resyncInterval: 60s
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "homescale"
        envSlug: "prod"
        secretsPath: "/k8s/volsync"
      credentialsRef:
        secretName: infisical-operator-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: time-machine-volsync-repo # pragma: allowlist secret
      secretNamespace: time-machine
      creationPolicy: Owner
      secretType: Opaque
      template:
        includeAllSecrets: true
        data:
          RESTIC_REPOSITORY: "{{`{{ .RESTIC_REPOSITORY.Value }}`}}/{{ .Values.cluster.name }}/time-machine"
