apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        k8s.v1.cni.cncf.io/networks: '[{"name":"vlan-wlan","namespace":"kube-system","ips":[{{ .Values.network.ip | quote }}]}]'
    spec:
      containers:
        - name: time-machine
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: ADVERTISED_HOSTNAME
              value: {{ .Values.timemachine.advertisedHostname | quote }}
            - name: MIMIC_MODEL
              value: {{ .Values.timemachine.mimicModel | quote }}
            - name: TM_VOLUME_NAME
              value: {{ .Values.timemachine.volumeName | quote }}
            - name: TM_UID
              value: {{ .Values.timemachine.uid | quote }}
            - name: TM_GID
              value: {{ .Values.timemachine.gid | quote }}
            - name: CUSTOM_USER
              value: "true"
          envFrom:
            - secretRef:
                name: time-machine
          ports:
            - containerPort: 445
              name: smb
          volumeMounts:
            - name: data
              mountPath: /opt/timemachine
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "DAC_READ_SEARCH"]
              drop: ["ALL"]
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.pvc.size }}
