{{- $pvc := "data-time-machine-0" -}}
{{- $schedule := ((.Values.volsync).backupSchedule) | default "0 3 * * *" -}}
{{- $restore := ((.Values.volsync).restore).enabled -}}
{{- if not $restore }}
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: {{ $pvc }}
  namespace: time-machine
spec:
  sourcePVC: {{ $pvc }}
  trigger:
    schedule: {{ $schedule | quote }}
  restic:
    repository: time-machine-volsync-repo # pragma: allowlist secret
    copyMethod: Snapshot
    retain:
      daily: 7
      weekly: 4
      monthly: 3
    pruneIntervalDays: 7
{{- end }}
{{- if $restore }}
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: {{ $pvc }}-restore
  namespace: time-machine
spec:
  trigger:
    manual: restore-once
  restic:
    repository: time-machine-volsync-repo # pragma: allowlist secret
    copyMethod: Direct
    destinationPVC: {{ $pvc }}
    {{- if (($.Values.volsync).restore).restoreAsOf }}
    restoreAsOf: {{ $.Values.volsync.restore.restoreAsOf | quote }}
    {{- end }}
    {{- if (($.Values.volsync).restore).previous }}
    previous: {{ $.Values.volsync.restore.previous }}
    {{- end }}
{{- end }}
