defaultDeploy: true

path: apps/spegel
namespace: spegel
releaseName: spegel
podSecurity: privileged
syncWave: -20
values:
  spegel:
    spegel:
      containerdRegistryConfigPath: /etc/cri/conf.d/hosts
