path: apps/homecraft
namespace: homecraft
releaseName: homecraft
syncWave: 0
defaultDeploy: false
clusters:
  boa1-prod:
    deploy: true
values:
  cluster:
    name: "{{ .Values.cluster.name }}"
  global:
    env: ""
  minecraft:
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
    minecraftServer:
      eula: "TRUE"
      memory: 2048M
      type: "PAPER"
      gameMode: "creative"
      ops: "m4xm0rris"
      motd: "HomeCraft - {{ .Values.cluster.name }}"
      icon: "https://avatars.githubusercontent.com/u/149919927?s=200&v=4"
    persistence:
      dataDir:
        enabled: true
        Size: "2Gi"
