path: apps/homecraft
namespace: homecraft
releaseName: homecraft
syncWave: 0
defaultDeploy: false
netbird:
  policy:
    rules:
      - sources: ["all"]
        protocol: tcp
        ports: ["25565"]
      - sources: ["all"]
        protocol: udp
        ports: ["25565"]
values:
  cluster:
    name: "{{ .Values.cluster.name }}"
  global:
    env: ""
  minecraft:
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
    minecraftServer:
      eula: "TRUE"
      memory: 2048M
      type: "PAPER"
      gameMode: "creative"
      ops: "m4xm0rris"
      motd: "HomeCraft - {{ .Values.cluster.name }}"
      icon: "https://raw.githubusercontent.com/HomeScaleCloud/.github/refs/heads/main/homecraft.png"
    extraEnv:
      MC_PORT: "25565"
    persistence:
      dataDir:
        enabled: true
        Size: "2Gi"
