apiVersion: v2
name: homecraft
description: Helm chart for deploying the Homecraft Minecraft server
type: application
version: 0.1.0
dependencies:
  - name: minecraft
    version: 5.1.3
    repository: https://itzg.github.io/minecraft-server-charts/
