apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backups-viewer
rules:
  - apiGroups: ["volsync.backube"]
    resources:
      - replicationsources
      - replicationdestinations
    verbs: ["get", "list", "watch"]
