apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backups-admin
rules:
  - apiGroups: ["volsync.backube"]
    resources:
      - replicationsources
      - replicationdestinations
    verbs: ["*"]
