apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-operator
rules:
  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs: ["create", "delete", "get", "list"]
  - apiGroups: ["batch"]
    resources:
      - cronjobs
    verbs: ["get"]
  - apiGroups: ["REDACTED"]
    resources:
      - jobruns
      - jobworkflowruns
    verbs: ["create", "get", "list"]
  - apiGroups: ["REDACTED"]
    resources:
      - jobtemplates
      - jobworkflows
    verbs: ["get", "list"]
