apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networking-viewer
rules:
  - apiGroups: [""]
    resources:
      - services
      - endpoints
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
      - ingresses
      - ingressclasses
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources:
      - endpointslices
    verbs: ["get", "list", "watch"]
  - apiGroups: ["traefik.io"]
    resources:
      - ingressroutes
      - ingressroutetcps
      - ingressrouteudps
      - middlewares
      - middlewaretcps
      - tlsoptions
      - tlsstores
      - traefikservices
      - serverstransports
      - serverstransporttcps
    verbs: ["get", "list", "watch"]
  - apiGroups: ["tailscale.com"]
    resources:
      - connectors
      - dnsconfigs
      - peerrelays
      - proxyclasses
      - proxygrouppolicies
      - proxygroups
      - recorders
      - tailnets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["crd.projectcalico.org"]
    resources:
      - bgpconfigurations
      - bgpfilters
      - bgppeers
      - blockaffinities
      - caliconodestatuses
      - clusterinformations
      - felixconfigurations
      - globalnetworkpolicies
      - globalnetworksets
      - hostendpoints
      - ipamblocks
      - ipamconfigs
      - ipamhandles
      - ippools
      - ipreservations
      - kubecontrollersconfigurations
      - networkpolicies
      - networksets
      - stagedglobalnetworkpolicies
      - stagedkubernetesnetworkpolicies
      - stagednetworkpolicies
      - tiers
    verbs: ["get", "list", "watch"]
  - apiGroups: ["cilium.io"]
    resources:
      - ciliumbgpadvertisements
      - ciliumbgpclusterconfigs
      - ciliumbgpnodeconfigoverrides
      - ciliumbgpnodeconfigs
      - ciliumbgppeerconfigs
      - ciliumcidrgroups
      - ciliumclusterwideenvoyconfigs
      - ciliumclusterwidenetworkpolicies
      - ciliumdatapathplugins
      - ciliumegressgatewaypolicies
      - ciliumendpoints
      - ciliumendpointslices
      - ciliumenvoyconfigs
      - ciliumgatewayclassconfigs
      - ciliumidentities
      - ciliuml2announcementpolicies
      - ciliumloadbalancerippools
      - ciliumlocalredirectpolicies
      - ciliumnetworkdriverclusterconfigs
      - ciliumnetworkdrivernodeconfigs
      - ciliumnetworkpolicies
      - ciliumnodeconfigs
      - ciliumnodes
      - ciliumpodippools
      - ciliumresourceippools
    verbs: ["get", "list", "watch"]
