apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: policy-viewer
rules:
  - apiGroups: ["kyverno.io"]
    resources:
      - cleanuppolicies
      - clustercleanuppolicies
      - clusterpolicies
      - globalcontextentries
      - policies
      - policyexceptions
      - updaterequests
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policies.kyverno.io"]
    resources:
      - deletingpolicies
      - generatingpolicies
      - imagevalidatingpolicies
      - mutatingpolicies
      - namespaceddeletingpolicies
      - namespacedgeneratingpolicies
      - namespacedimagevalidatingpolicies
      - namespacedmutatingpolicies
      - namespacedvalidatingpolicies
      - policyexceptions
      - validatingpolicies
    verbs: ["get", "list", "watch"]
  - apiGroups: ["reports.kyverno.io", "wgpolicyk8s.io"]
    resources:
      - clusterephemeralreports
      - ephemeralreports
      - clusterpolicyreports
      - policyreports
    verbs: ["get", "list", "watch"]
