apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storage-viewer
rules:
  - apiGroups: [""]
    resources:
      - persistentvolumeclaims
      - persistentvolumes
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
      - volumeattachments
      - volumeattributesclasses
    verbs: ["get", "list", "watch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources:
      - volumesnapshots
      - volumesnapshotclasses
      - volumesnapshotcontents
    verbs: ["get", "list", "watch"]
  - apiGroups: ["volsync.backube"]
    resources:
      - replicationsources
      - replicationdestinations
    verbs: ["get", "list", "watch"]
