apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workloads-viewer
rules:
  - apiGroups: [""]
    resources:
      - pods
      - configmaps
      - replicationcontrollers
      - namespaces
      - resourcequotas
      - limitranges
      - events
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: ["cert-manager.io"]
    resources:
      - "*"
    verbs: ["get", "list", "watch"]
  - apiGroups: ["secrets.infisical.com"]
    resources:
      - "*"
    verbs: ["get", "list", "watch"]
