apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sg-k8s-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: sg-k8s-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sg-k8s-admin:workloads-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workloads-admin
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: sg-k8s-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sg-k8s-admin:node-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-admin
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: sg-k8s-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sg-k8s-admin:networking-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: networking-admin
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: sg-k8s-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sg-k8s-admin:storage-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storage-admin
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: sg-k8s-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sg-k8s-admin:rbac-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rbac-admin
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: sg-k8s-admin
