apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-boa1-gw
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: git@github.com:HomeScaleCloud/homescale.git
      targetRevision: main
      path: clusters/boa1-gw
      directory:
        recurse: true
        exclude: 'cluster.yaml'
    - repoURL: git@github.com:HomeScaleCloud/homescale.git
      targetRevision: main
      path: apps
      helm:
        releaseName: apps-boa1-gw
        values: |
          cluster:
            name: boa1-gw
            region: boa1
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /metadata/finalizers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
