defaultDeploy: false

clusters:
  mgmt:
    deploy: true

path: apps/external-dns
namespace: external-dns
releaseName: external-dns
syncWave: -10
values:
  external-dns:
    sources:
      - service
      - ingress
    provider:
      name: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare
            key: credential
    domainFilters: ["xxx"]
