apiVersion: v2
name: external-dns
description: Helm chart for deploying external-dns
type: application
version: 0.1.0
dependencies:
  - name: external-dns
    version: 1.20.0
    repository: https://kubernetes-sigs.github.io/external-dns/
