defaultDeploy: false

path: apps/rook-ceph-cluster-boa1
namespace: rook-ceph-boa1
releaseName: boa1
podSecurity: privileged
syncWave: 0

clusters:
  prod:
    deploy: true
    values:
      rook-ceph-cluster:
        operatorNamespace: rook-ceph
        clusterName: boa1
        cephClusterSpec:
          network:
            provider: host
          storage:
            useAllNodes: true
            useAllDevices: true
            config:
              minSize: "900G"
          resources:
            mon:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 1Gi
            mgr:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 1Gi
            osd:
              requests:
                cpu: 500m
                memory: 2Gi
              limits:
                memory: 4Gi
            crashcollector:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 64Mi
            logcollector:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 128Mi
            exporter:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 128Mi
          placement:
            all:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: xxx/region
                          operator: In
                          values:
                            - boa1
