apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: egress
spec:
  type: egress
  replicas: 3
  hostnamePrefix: 'egress-{{ required "cluster.name is required" .Values.cluster.name }}'
  tags:
    - 'tag:k8s'
    - 'tag:cluster-{{ required "cluster.name is required" .Values.cluster.name }}'
