apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: k8s-tailscale
spec:
  syncConfig:
    resyncInterval: 60s
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "homescale"
        envSlug: "prod"
        secretsPath: "/k8s/tailscale"
      credentialsRef:
        secretName: infisical-operator-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: operator-oauth
      secretNamespace: tailscale
      creationPolicy: Owner
      secretType: Opaque
