apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: {{ .Release.Name }}-{{ required "cluster.name is required" .Values.cluster.name }}
spec:
  networkRouterRef:
    name: '{{ required "cluster.name is required" .Values.cluster.name }}'
    namespace: netbird
  serviceRef:
    name: {{ .Release.Name }}
  groups:
    - name: app-homepage
    - name: cluster-{{ required "cluster.name is required" .Values.cluster.name }}
