apiVersion: netbird.io/v1alpha1
kind: ClusterProxy
metadata:
  name: netbird-clusterproxy
  namespace: netbird
spec:
  clusterName: {{ required "cluster.name is required" .Values.cluster.name }}
  serviceAccountName: netbird-clusterproxy
  groups:
    - name: k8s
    - name: cluster-{{ required "cluster.name is required" .Values.cluster.name }}
