apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: k8s
  namespace: default
spec:
  networkRouterRef:
    name: '{{ required "cluster.name is required" .Values.cluster.name }}'
    namespace: netbird
  serviceRef:
    name: kubernetes
  groups:
    - name: k8s
    {{- if eq .Values.cluster.name "mgmt" }}
    - name: cluster-mgmt
    {{- else }}
    - name: cluster-{{ required "cluster.name is required" .Values.cluster.name }}
    {{- end }}
