apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: kubernetes-apiserver
  namespace: default
spec:
  networkRouterRef:
    name: '{{ required "cluster.name is required" .Values.cluster.name }}'
    namespace: netbird
  serviceRef:
    name: kubernetes
  groups:
    - name: k8s
    - name: cluster-{{ required "cluster.name is required" .Values.cluster.name }}
