defaultDeploy: true

path: apps/onepassword
namespace: onepassword
releaseName: onepassword
syncWave: -35
values:
  connect:
    connect:
      serviceType: ClusterIP
      credentialsName: onepassword
      credentialsKey: credential
    operator:
      create: true
      token:
        name: onepassword
        key: password
