apiVersion: v2
name: traefik-private
description: Helm chart for deploying Traefik (private services via ClusterIP/NetBird)
type: application
version: 0.1.0
dependencies:
  - name: traefik
    version: 41.0.2
    repository: https://traefik.github.io/charts
