apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: k8s-${ .ClusterName }-${ get .ClusterLabels "cluster.homescale.cloud/region" }
spec:
  type: kube-apiserver
  replicas: {{ .Values.kubeProxy.replicas }}
  tags: ["tag:k8s", "tag:env-${ get .ClusterLabels \"cluster.homescale.cloud/env\" }"]
  kubeAPIServer:
    mode: auth
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: ingress
spec:
  type: ingress
  replicas: {{ .Values.ingressProxy.replicas }}
  tags: ["tag:app", "tag:env-${ get .ClusterLabels \"cluster.homescale.cloud/env\" }"]
  hostnamePrefix: ingress-${ .ClusterName }-${ get .ClusterLabels "cluster.homescale.cloud/region" }
