apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-core
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: git@github.com:HomeScaleCloud/homescale.git
      targetRevision: main
      path: clusters/core
      directory:
        recurse: true
        exclude: 'cluster.yaml'
    - repoURL: git@github.com:HomeScaleCloud/homescale.git
      targetRevision: main
      path: infra/automatron
      directory:
        recurse: true
    - repoURL: git@github.com:HomeScaleCloud/homescale.git
      targetRevision: main
      path: apps
      helm:
        releaseName: apps-core
        values: |
          cluster:
            name: core
          apps:
            automatron:
              deploy: true
            cilium:
              deploy: false
            cloudflared:
              deploy: true
              values:
                cluster:
                  name: core
            headlamp:
              deploy: true
            kro:
              deploy: true
            multus:
              deploy: false
            node-inotify-limits:
              deploy: true
            omni:
              deploy: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /metadata/finalizers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
