apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: automatron-jobs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:HomeScaleCloud/homescale.git
    targetRevision: main
    path: infra/automatron
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: automatron
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
