apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-cloudflare
  namespace: cert-manager
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "homescale"
        envSlug: "production"
        secretsPath: "/k8s/cloudflare"
      credentialsRef:
        secretName: infisical-operator-auth
        secretNamespace: infisical
  managedSecretReference:
    secretName: cloudflare
    secretNamespace: cert-manager
