apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: k8s-cloudflare
  namespace: cert-manager
spec:
  syncConfig:
    resyncInterval: 60s
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "homescale"
        envSlug: "prod"
        secretsPath: "/k8s/cloudflare"
      credentialsRef:
        secretName: infisical-operator-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: cloudflare
      secretNamespace: cert-manager
