apiVersion: v2
name: metrics
description: Helm chart for deploying HomeScale metrics stack
type: application
version: 0.1.0
dependencies:
  - name: kube-prometheus-stack
    version: 81.6.9
    repository: https://prometheus-community.github.io/helm-charts
  - name: metrics-server
    version: 3.13.0
    repository: https://kubernetes-sigs.github.io/metrics-server/
