apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  annotations:
    avp-kustomize.kubernetes.io/path: "vaults/core/items/argocd"
resources:
  - ../../../base/manifests
patches:

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: omni
      namespace: omni
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --siderolink-api-advertised-url=https://xxx:8095/
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --advertised-kubernetes-proxy-url=https://xxx/
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --siderolink-wireguard-advertised-addr=xxx:50180
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --advertised-api-url=https://xxx/
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --auth-saml-url=<path:vaults/core/items/omni#saml-url>

  - target:
      group: onepassword.com
      version: v1
      kind: OnePasswordItem
      name: op-omni
    patch: |-
      - op: add
        path: /spec/itemPath
        value: "vaults/core/items/omni"

  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: omni-ui
      namespace: omni
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: xxx
      - op: replace
        path: /spec/tls/0/hosts
        value:
          - xxx
          - xxx
          - xxx

  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: omni-k8s
      namespace: omni
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: xxx
      - op: replace
        path: /spec/tls/0/hosts
        value:
          - xxx
          - xxx
          - xxx

  - target:
      kind: Service
      name: omni
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          external-dns.alpha.kubernetes.io/hostname: xxx.