# All secrets are fetched from Infisical in GitHub Actions before Terraform runs
# (via infisical/secrets-action with OIDC) and passed as TF_VAR_* env vars.
# Secrets generated by Terraform (kubeconfigs, tokens) are written back to
# Infisical using the infisical_secret resource in the relevant module.
