---
argocd_deploy_key: "{{ lookup('env', 'sshPrivateKey') }}"
infisical_operator_client_id: "{{ lookup('env', 'INFISICAL_OPERATOR_CLIENT_ID') }}"
infisical_operator_client_secret: "{{ lookup('env', 'INFISICAL_OPERATOR_CLIENT_SECRET') }}"
