path: apps/home-assistant
namespace: home-assistant
releaseName: home-assistant
syncWave: 0
values:
  image:
    repository: ghcr.io/home-assistant/home-assistant
    tag: "2025.12.5"
  ingress:
    enabled: true
    className: tailscale
    host: "ha-{{ .Values.global.cluster }}-{{ .Values.global.region }}.REDACTED"
    annotations:
      tailscale.com/hostname: "ha-{{ .Values.global.cluster }}-{{ .Values.global.region }}"
      tailscale.com/tags: "tag:app-ha,tag:env-{{ .Values.global.env }}"
  pvc:
    size: 25Gi
  zigbee:
    local: true
    devicePath: /dev/ttyUSB0
