path: apps/omni
namespace: omni
releaseName: omni
syncWave: 0
netbird:
  policy:
    rules:
      - sources: ["github-actions", "team-infra-plat", "team-sec-plat"]
        protocol: tcp
        ports: ["80", "443"]

values:
  cluster:
    name: "{{ .Values.cluster.name }}"
  siderolinkHostname: xxx
  machineApiHostname: xxx
  omni:
    etcdEncryptionKey:
      existingSecret: omni # pragma: allowlist secret

    additionalConfigSources:
      - existingSecret: omni  # pragma: allowlist secret
        key: config.yaml

    config:
      account:
        id: 7848e298-4d35-4c33-a4c8-6659160b6afb
        name: HomeScale
      auth:
        auth0:
          enabled: false
        saml:
          enabled: true
          labelRules:
            "http://schemas.microsoft.com/ws/2008/06/identity/claims/groups": "groups"
      features:
        enableBreakGlassConfigs: true
      services:
        api:
          advertisedURL: "https://xxx"
          certFile: /tls/tls.crt
          keyFile: /tls/tls.key
        kubernetesProxy:
          advertisedURL: "https://xxx"
          certFile: /tls/tls.crt
          keyFile: /tls/tls.key
        machineAPI:
          advertisedURL: "https://xxx"
          certFile: /tls/tls.crt
          keyFile: /tls/tls.key
        siderolink:
          useGRPCTunnel: true
          wireGuard:
            advertisedEndpoint: "xxx:50180"

    service:
      wireguard:
        type: ClusterIP

    ingress:
      main:
        enabled: false
      kubernetesProxy:
        enabled: false
      siderolinkApi:
        enabled: false

    extraVolumes:
      - name: omni-tls
        secret:
          secretName: omni-tls

    extraVolumeMounts:
      - name: omni-tls
        mountPath: /tls
        readOnly: true

    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: omni
        scheme: HTTPS
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3

    persistence:
      enabled: true
      size: 25Gi
      existingClaim: omni

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
