clusters:
  mgmt:
    deploy: true

path: apps/omni
namespace: omni
releaseName: omni
syncWave: 0
values:
  cluster:
    name: "{{ .Values.cluster.name }}"
  omni:
    etcdEncryptionKey:
      existingSecret: op-omni # pragma: allowlist secret

    additionalConfigSources:
      - existingSecret: op-omni  # pragma: allowlist secret
        key: config.yaml

    config:
      account:
        id: 7848e298-4d35-4c33-a4c8-6659160b6afb
        name: homescale
      auth:
        auth0:
          enabled: false
        saml:
          enabled: true
      services:
        initialServiceAccount:
          enabled: true
          name: bootstrap
          role: Admin
          keyPath: /data/initial-sa-key
          lifetime: 24h
        api:
          advertisedURL: "https://REDACTED"
          certFile: /tls/tls.crt
          keyFile: /tls/tls.key
        kubernetesProxy:
          advertisedURL: "https://REDACTED"
          certFile: /tls/tls.crt
          keyFile: /tls/tls.key
        machineAPI:
          advertisedURL: "https://REDACTED"
          certFile: /tls/tls.crt
          keyFile: /tls/tls.key
        siderolink:
          wireGuard:
            advertisedEndpoint: "REDACTED:50180"

    service:
      wireguard:
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: REDACTED

    ingress:
      main:
        enabled: false
      kubernetesProxy:
        enabled: false
      siderolinkApi:
        enabled: false

    extraVolumes:
      - name: omni-tls
        secret:
          secretName: omni-tls

    extraVolumeMounts:
      - name: omni-tls
        mountPath: /tls
        readOnly: true

    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: omni
        scheme: HTTPS
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 3

    persistence:
      enabled: true
      size: 16Gi
