apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: k8s
  namespace: default
spec:
  networkRouterRef:
    name: '{{- if eq .Values.cluster.name "mgmt" -}}{{ .Values.cluster.name }}{{- else -}}{{ required "cluster.name is required" .Values.cluster.name }}-{{ required "cluster.region is required unless cluster.name is mgmt" .Values.cluster.region }}{{- end }}'
    namespace: netbird
  serviceRef:
    name: kubernetes
  groups:
    - name: k8s
    {{- if eq .Values.cluster.name "mgmt" }}
    - name: cluster-mgmt
    - name: env-mgmt
    {{- else }}
    - name: cluster-{{ required "cluster.name is required" .Values.cluster.name }}
    - name: region-{{ required "cluster.region is required unless cluster.name is mgmt" .Values.cluster.region }}
    - name: env-{{ required "cluster.env is required unless cluster.name is mgmt" .Values.cluster.env }}
    {{- end }}
