apiVersion: v2
name: slurm
description: Helm chart for a Slinky Slurm cluster (Cluster/NodeSet CRs managed by slurm-operator)
type: application
version: 0.1.0
dependencies:
  - name: slurm
    version: 1.2.2
    repository: oci://ghcr.io/slinkyproject/charts
