defaultNamespace: traefik
name: traefik-private
helm:
  releaseName: traefik-private
  chart: ./
  takeOwnership: true
  force: true
  values:
    traefik:
      deployment:
        replicas: 2
      service:
        type: ClusterIP
      ingressClass:
        enabled: true
        name: traefik-private
        isDefaultClass: true
      providers:
        kubernetesIngress:
          enabled: true
          ingressClass: traefik-private
          labelSelector: xxx/class=private
          publishedService:
            enabled: true
        kubernetesCRD:
          enabled: true
          ingressClass: traefik-private
          labelSelector: xxx/class=private
      additionalArguments:
        - "--providers.kubernetesingress.ingressclass=traefik-private"
