argocd:
  namespace: argocd

project: default
repoURL: git@github.com:HomeScaleCloud/homescale.git
targetRevision: main
applicationNamePrefix: ""
revisionHistoryLimit: 10

cluster:
  name: ""
  region: ""

destination:
  name: ""
  server: https://kubernetes.default.svc

syncPolicy:
  automated:
    prune: true
    selfHeal: true

syncOptions:
  - CreateNamespace=true

apps: {}
