#!/bin/bash
# Script to quickly switch k8s cluster/namespaces via Teleport

# Get Teleport clusters
clusters=$(tsh kube ls --format=json | jq -r 'map(.kube_cluster_name) | join("\n")' 2>/dev/null)

# Use fzf to pick a cluster
cluster=$(echo "$clusters" | fzf --prompt="Cluster: " --height=10 --reverse)

if [[ -z "$cluster" ]]; then
  echo "No cluster selected."
  return 1 2>/dev/null || exit 1
fi

# Login to the selected Teleport cluster
tsh kube login "$cluster" >/dev/null || exit 1

# Pick namespace
namespace=$(kubectl get namespaces -o jsonpath='{.items[*].metadata.name}' 2>/dev/null | tr " " "\n" | fzf --prompt="Namespace: " --height=10 --reverse)
namespace=${namespace:-default}
kubectl config set-context --current --namespace="$namespace" >/dev/null
echo "Logged into $cluster $namespace"
