{{- range $clusterName, $config := .Values.clusters }}
{{- $ns := $config.namespace }}
{{- range $pool := default (list) $config.blockPools }}
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: {{ $pool.name }}
  namespace: {{ $ns }}
spec:
{{ toYaml $pool.spec | nindent 2 }}
{{- if and $pool.storageClass $pool.storageClass.enabled }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ required (printf "blockPools[%s].storageClass.name is required" $pool.name) $pool.storageClass.name }}
  {{- if $pool.storageClass.isDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: {{ $ns }}.rbd.csi.ceph.com
parameters:
  clusterID: {{ $ns }}
  pool: {{ $pool.name }}
  imageFormat: "2"
  imageFeatures: layering
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: {{ $ns }}
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ $ns }}
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
  csi.storage.k8s.io/node-stage-secret-namespace: {{ $ns }}
  {{- with $pool.storageClass.parameters }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
reclaimPolicy: {{ default "Delete" $pool.storageClass.reclaimPolicy }}
allowVolumeExpansion: true
{{- end }}
{{- end }}
{{- end }}
