{{- range $clusterName, $config := .Values.clusters }}
{{- $ns := $config.namespace }}
{{- range $fs := default (list) $config.filesystems }}
---
apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: {{ $fs.name }}
  namespace: {{ $ns }}
spec:
{{ toYaml $fs.spec | nindent 2 }}
{{- if and $fs.storageClass $fs.storageClass.enabled }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ required (printf "filesystems[%s].storageClass.name is required" $fs.name) $fs.storageClass.name }}
  {{- if $fs.storageClass.isDefault }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: {{ $ns }}.cephfs.csi.ceph.com
parameters:
  clusterID: {{ $ns }}
  fsName: {{ $fs.name }}
  pool: {{ $fs.name }}-data0
  csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/provisioner-secret-namespace: {{ $ns }}
  csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ $ns }}
  csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
  csi.storage.k8s.io/node-stage-secret-namespace: {{ $ns }}
  {{- with $fs.storageClass.parameters }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
reclaimPolicy: {{ default "Delete" $fs.storageClass.reclaimPolicy }}
allowVolumeExpansion: true
{{- end }}
{{- end }}
{{- end }}
