---
- name: Check if Cilium is already installed
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: DaemonSet
    name: cilium
    namespace: kube-system
  register: _cilium_ds

- name: Install Cilium
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium
    chart_repo_url: https://helm.cilium.io/
    chart_version: "{{ cilium_chart_version }}"
    release_namespace: kube-system
    create_namespace: false
    state: present
    wait: true
    wait_timeout: "300s"
    values:
      kubeProxyReplacement: true
      k8sServiceHost: localhost
      k8sServicePort: 7445
      ipam:
        mode: kubernetes
      cgroup:
        autoMount:
          enabled: false
        hostRoot: /sys/fs/cgroup
      securityContext:
        capabilities:
          ciliumAgent:
            - CHOWN
            - KILL
            - NET_ADMIN
            - NET_RAW
            - IPC_LOCK
            - SYS_ADMIN
            - SYS_RESOURCE
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID
          cleanCiliumState:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_RESOURCE
  when: _cilium_ds.resources | length == 0
