path: apps/traefik-public
namespace: traefik
releaseName: traefik-public
syncWave: 0
values:
  traefik:
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: 'ingress.{{ .Values.cluster.name }}xxx'
