apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlas-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:HomeScaleCloud/homescale.git
    targetRevision: main
    path: apps
    helm:
      releaseName: atlas-apps
      values: |
        repoURL: git@github.com:HomeScaleCloud/homescale.git

        cluster:
          name: atlas
          region: boa1
          env: metal

        destination:
          server: https://kubernetes.default.svc

        apps:
          argocd:
            enabled: true
          cert-manager:
            enabled: true
          cert-manager-crs:
            enabled: true
          onepassword:
            enabled: true
          rbac:
            enabled: true
          netbird:
            enabled: true
          netbird-crs:
            enabled: true
          external-dns:
            enabled: true
          external-dns-crs:
            enabled: true
          home-assistant:
            enabled: true
          # homepage:
          #   enabled: true
          metrics-legacy:
            enabled: true
          minecraft:
            enabled: true
          traefik-private:
            enabled: true
          traefik-public:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
