path: apps/netbird
namespace: netbird
releaseName: netbird
syncWave: -20
podSecurity: privileged
syncOptions:
  - ServerSideApply=true
defaultDeploy: true
values:
  netbird-operator:
    cluster:
      name: '{{ .Values.cluster.name }}'
    operator:
      replicaCount: 2
    webhook:
      failurePolicy: Ignore
    netbirdAPI:
      keyFromSecret:
        name: netbird
        key: NETBIRD_OPERATOR_TOKEN
ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: netbird-kubernetes-operator-mpod-webhook
    jsonPointers:
      - /webhooks
