apiVersion: v2
name: netbird
description: Helm chart for NetBird Operator
type: application
version: 0.1.0
dependencies:
  - name: kubernetes-operator
    version: 0.3.1
    repository: https://netbirdio.github.io/helms
