apiVersion: twingate.com/v1beta
kind: TwingateResource
metadata:
  name: mgmt
spec:
  name: mgmt
  address: rancher.cattle-system.svc.cluster.local
  alias: mgmt.homescale.cloud
  securityPolicyId: U2VjdXJpdHlQb2xpY3k6MTA2MDEzMA
