apiVersion: twingate.com/v1beta
kind: TwingateResource
metadata:
  name: mgmt
  namespace: cattle-system
spec:
  name: mgmt
  address: rancher.cattle-system.svc.cluster.local
  alias: mgmt.homescale.cloud
  securityPolicyId: U2VjdXJpdHlQb2xpY3k6MTA2MDEzMA==
  isBrowserShortcutEnabled: true
---
apiVersion: twingate.com/v1beta
kind: TwingateResourceAccess
metadata:
  name: mgmt-team-infra-plat
spec:
  resourceRef:
    name: mgmt
    namespace: cattle-system
  principalExternalRef:
    type: group
    name: team-infra-plat
---
apiVersion: twingate.com/v1beta
kind: TwingateResourceAccess
metadata:
  name: mgmt-team-sec-plat
spec:
  resourceRef:
    name: mgmt
    namespace: cattle-system
  principalExternalRef:
    type: group
    name: team-sec-plat
