path: apps/minecraft
namespace: minecraft
releaseName: minecraft
syncWave: 0
values:
  global:
    env: ""
  minecraft:
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
    minecraftServer:
      eula: "TRUE"
      memory: 2048M
    persistence:
      dataDir:
        enabled: true
        Size: "2Gi"
