apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: omni-tls
  namespace: omni
spec:
  secretName: omni-tls
  issuerRef:
    name: {{ .Values.certIssuer | default "letsencrypt" }}
    kind: ClusterIssuer
  dnsNames:
    - omni.{{ required "cluster.name is required" .Values.cluster.name }}xxx
    - k8s.api.omni.{{ required "cluster.name is required" .Values.cluster.name }}xxx
    - {{ required "siderolinkHostname is required" .Values.siderolinkHostname }}
    - {{ required "machineApiHostname is required" .Values.machineApiHostname }}
