apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: omni-tls
  namespace: omni
spec:
  secretName: omni-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - xxx
    - xxx
    - xxx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd-tls
  namespace: omni
spec:
  secretName: etcd-tls # pragma: allowlist secret
  issuerRef:
    name: omni-etcd-ca
    kind: ClusterIssuer
  commonName: etcd.omni.svc.cluster.local
  dnsNames:
    - etcd.omni.svc.cluster.local
    - etcd.omni.svc
    - etcd-headless.omni.svc.cluster.local
    - etcd-headless.omni.svc
    - "*.etcd-headless.omni.svc.cluster.local"
    - "*.etcd-headless.omni.svc"
    - localhost
  ipAddresses:
    - 127.0.0.1
  usages:
    - server auth
    - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: omni-etcd-client
  namespace: omni
spec:
  secretName: omni-etcd-client # pragma: allowlist secret
  issuerRef:
    name: omni-etcd-ca
    kind: ClusterIssuer
  commonName: omni
  usages:
    - client auth
