apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: k8s-omni
  namespace: omni
spec:
  syncConfig:
    resyncInterval: 60s
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "homescale"
        envSlug: "prod"
        secretsPath: "/k8s/omni"
      credentialsRef:
        secretName: infisical-operator-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: omni
      secretNamespace: omni
      creationPolicy: Owner
      secretType: Opaque
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: k8s-volsync-omni
  namespace: omni
spec:
  syncConfig:
    resyncInterval: 60s
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "homescale"
        envSlug: "prod"
        secretsPath: "/k8s/volsync"
      credentialsRef:
        secretName: infisical-operator-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: omni-volsync-repo # pragma: allowlist secret
      secretNamespace: omni
      creationPolicy: Owner
      secretType: Opaque
      template:
        includeAllSecrets: true
        data:
          RESTIC_REPOSITORY: "{{`{{ .RESTIC_REPOSITORY.Value }}`}}/{{ .Values.cluster.name }}/omni"
