apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: omni
spec:
  selector:
    app.kubernetes.io/instance: omni
    app.kubernetes.io/name: omni
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: k8s
  namespace: omni
spec:
  selector:
    app.kubernetes.io/instance: omni
    app.kubernetes.io/name: omni
  ports:
    - name: https
      port: 443
      targetPort: 8095
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ required "siderolinkHostname is required" .Values.siderolinkHostname }}
    service.beta.kubernetes.io/vultr-loadbalancer-backend-protocol: "udp"
    service.beta.kubernetes.io/vultr-loadbalancer-protocol: "udp"
  name: siderolink
  namespace: omni
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: omni
    app.kubernetes.io/name: omni
  ports:
    - name: wireguard
      port: 50180
      protocol: UDP
      targetPort: wireguard
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ required "machineApiHostname is required" .Values.machineApiHostname }}
  name: machine-api
  namespace: omni
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: omni
    app.kubernetes.io/name: omni
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8090
