apiVersion: v1
kind: Service
metadata:
  name: k8s
  namespace: omni
spec:
  selector:
    app.kubernetes.io/instance: omni
    app.kubernetes.io/name: omni
  ports:
    - port: 443
      targetPort: 8095
