{{- if not ((.Values.volsync).restore).enabled }}
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: omni
  namespace: omni
spec:
  sourcePVC: omni
  trigger:
    schedule: {{ (.Values.volsync).backupSchedule | default "0 */2 * * *" | quote }}
  restic:
    repository: omni-volsync-repo # pragma: allowlist secret
    copyMethod: Direct
    retain:
      daily: 7
      weekly: 4
      monthly: 3
    pruneIntervalDays: 7
{{- end }}
{{- if ((.Values.volsync).restore).enabled }}
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: omni-restore
  namespace: omni
spec:
  trigger:
    manual: restore-once
  restic:
    repository: omni-volsync-repo # pragma: allowlist secret
    copyMethod: Direct
    destinationPVC: omni
    {{- if ((.Values.volsync).restore).restoreAsOf }}
    restoreAsOf: {{ .Values.volsync.restore.restoreAsOf | quote }}
    {{- end }}
    {{- if ((.Values.volsync).restore).previous }}
    previous: {{ .Values.volsync.restore.previous }}
    {{- end }}
{{- end }}
