name: "CI"
permissions:
  actions: read
  contents: write
  packages: write
  id-token: write
  issues: write
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scan:
    uses: ./.github/workflows/scan.yaml
    with:
      pr_title: ${{ github.event.pull_request.title }}
    secrets: inherit  # pragma: allowlist secret

  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit  # pragma: allowlist secret

  deploy:
    uses: ./.github/workflows/deploy.yaml
    needs: [scan]
    secrets: inherit  # pragma: allowlist secret

  mirror:
    uses: ./.github/workflows/mirror.yaml
    needs: [scan]
    if: github.event_name == 'push'
    secrets: inherit  # pragma: allowlist secret
