apiVersion: netbird.io/v1alpha1
kind: NetworkResource
metadata:
  name: argocd
  namespace: argocd
spec:
  networkRouterRef:
    name: '{{ required "cluster.name is required" .Values.cluster.name }}'
    namespace: netbird
  serviceRef:
    name: argocd-server
  groups:
    - name: app-argocd
    - name: cluster-{{ required "cluster.name is required" .Values.cluster.name }}
