apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: k8s-argocd
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  syncConfig:
    resyncInterval: 60s
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "homescale"
        envSlug: "prod"
        secretsPath: "/k8s/argocd"
      credentialsRef:
        secretName: infisical-operator-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: argocd-saml
      secretNamespace: argocd
      creationPolicy: Owner
      secretType: Opaque
    - secretName: argocd-notifications-secret
      secretNamespace: argocd
      creationPolicy: Owner
      secretType: Opaque
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: k8s-argocd-deploy-key
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  syncConfig:
    resyncInterval: 60s
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "homescale"
        envSlug: "prod"
        secretsPath: "/k8s/argocd/deploy-key"
      credentialsRef:
        secretName: infisical-operator-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: homescale-k8s-deploy-key # pragma: allowlist secret
      secretNamespace: argocd
      creationPolicy: Owner
      secretType: Opaque
      template:
        metadata:
          labels:
            argocd.argoproj.io/secret-type: repository
