defaultDeploy: true

path: apps/argocd
namespace: argocd
releaseName: argocd
syncWave: -30
syncOptions:
  - ServerSideApply=true
ignoreDifferences:
  - group: ""
    kind: Secret
    name: argocd-secret
    jsonPointers:
      - /data
values:
  cluster:
    name: "{{ .Values.cluster.name }}"
  argo-cd:
    crds:
      install: true
    configs:
      cm:
        admin.enabled: "false"
        timeout.reconciliation: "30s"
        url: "https://argocd-server.argocd.{{ .Values.cluster.name }}REDACTED"
        dex.config: |
          connectors:
            - type: saml
              id: saml
              name: Entra ID
              config:
                ssoURL: "$argocd-saml:entra-saml-sso-url"
                caData: "$argocd-saml:entra-saml-ca"
                redirectURI: "https://argocd-server.argocd.{{ .Values.cluster.name }}REDACTED/api/dex/callback"
                entityIssuer: "https://argocd-server.argocd.{{ .Values.cluster.name }}REDACTED/api/dex/callback"
                usernameAttr: email
                emailAttr: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
                groupsAttr: "http://schemas.microsoft.com/ws/2008/06/identity/claims/groups"
                nameIDPolicyFormat: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
      rbac:
        scopes: "[groups]"
        policy.default: '{{ if eq .Values.cluster.name "lab" }}role:admin{{ end }}'
        policy.csv: |
          g, sg-k8s-admin, role:admin
          g, team-infra-plat, role:readonly
          p, team-infra-plat, applications, delete/*/Pod/*/*, */*, allow
          p, team-infra-plat, applications, sync, */*, allow
      params:
        application.operations.selfHealTimeout: "5"
    notifications:
      enabled: true
      secret:
        create: false
      argocdUrl: "https://argocd-server.argocd.{{ .Values.cluster.name }}REDACTED"
      notifiers:
        service.slack: |
          token: $slack-token
        service.github: |
          appID: $github-status-app-id
          installationID: $github-status-app-installation-id
          privateKey: $github-status-app-private-key
      subscriptions:
        - recipients:
            - slack:alerts-infra-plat
          triggers:
            - on-sync-failed
            - on-health-degraded
            - on-app-errored
        - recipients:
            - github
          triggers:
            - on-sync-running
            - on-out-of-sync
            - on-sync-succeeded
            - on-sync-errored
            - on-health-degraded
            - on-app-errored
      triggers:
        trigger.on-sync-running: |
          - when: app.status.operationState.phase == 'Running'
            send: [app-github-status-syncing]
            oncePer: app.status.operationState.startedAt
        trigger.on-out-of-sync: |
          - when: app.status.sync.status == 'OutOfSync'
            send: [app-github-status-pending]
            oncePer: app.status.sync.revision
        trigger.on-sync-failed: |
          - when: app.status.operationState.phase in ['Error', 'Failed']
            send: [app-sync-failed]
        trigger.on-health-degraded: |
          - when: app.status.health.status in ['Degraded', 'Missing', 'Unknown']
            send: [app-health-degraded, app-github-status-degraded]
        trigger.on-sync-succeeded: |
          - when: app.status.operationState.phase == 'Succeeded' && app.status.health.status == 'Healthy'
            send: [app-github-status-success]
            oncePer: app.status.operationState.startedAt
          - when: app.status.operationState.phase == 'Succeeded' && app.status.health.status in ['Degraded', 'Missing', 'Unknown']
            send: [app-github-status-degraded]
            oncePer: app.status.operationState.startedAt
        trigger.on-sync-errored: |
          - when: app.status.operationState.phase in ['Error', 'Failed']
            send: [app-github-status-failure]
            oncePer: app.status.operationState.startedAt
        trigger.on-app-errored: |
          - when: any(app.status.conditions, {.type in ['InvalidSpecError', 'ComparisonError', 'SyncError']})
            send: [app-errored, app-github-status-degraded]
      templates:
        template.app-sync-failed: |
          message: |
            App {{ "{{" }}.app.metadata.name{{ "}}" }} failed to sync on cluster {{ "{{" }} index .app.metadata.labels "REDACTED/name" {{ "}}" }}
          slack:
            attachments: |
              [{
                "title": "{{ "{{" }}.app.metadata.name{{ "}}" }}",
                "title_link": "{{ "{{" }}.context.argocdUrl{{ "}}" }}/applications/{{ "{{" }}.app.metadata.name{{ "}}" }}",
                "color": "#E96D76",
                "fields": [
                  {"title": "Phase", "value": "{{ "{{" }}.app.status.operationState.phase{{ "}}" }}", "short": true},
                  {"title": "Cluster", "value": "{{ "{{" }} index .app.metadata.labels "REDACTED/name" {{ "}}" }}", "short": true},
                  {"title": "Message", "value": "{{ "{{" }}.app.status.operationState.message{{ "}}" }}", "short": false}
                ]
              }]
        template.app-health-degraded: |
          message: |
            App {{ "{{" }}.app.metadata.name{{ "}}" }} is in a degraded state on cluster {{ "{{" }} index .app.metadata.labels "REDACTED/name" {{ "}}" }}
          slack:
            attachments: |
              [{
                "title": "{{ "{{" }}.app.metadata.name{{ "}}" }}",
                "title_link": "{{ "{{" }}.context.argocdUrl{{ "}}" }}/applications/{{ "{{" }}.app.metadata.name{{ "}}" }}",
                "color": "#E96D76",
                "fields": [
                  {"title": "Health", "value": "{{ "{{" }}.app.status.health.status{{ "}}" }}", "short": true},
                  {"title": "Cluster", "value": "{{ "{{" }} index .app.metadata.labels "REDACTED/name" {{ "}}" }}", "short": true},
                  {"title": "Degraded Resources", "value": "{{ "{{" }}range .app.status.resources{{ "}}" }}{{ "{{" }}if and .health (eq .health.status `Degraded`){{ "}}" }}{{ "{{" }}.kind{{ "}}" }}/{{ "{{" }}.name{{ "}}" }}: {{ "{{" }}.health.message{{ "}}" }} {{ "{{" }}end{{ "}}" }}{{ "{{" }}end{{ "}}" }}", "short": false}
                ]
              }]
        template.app-errored: |
          message: |
            App {{ "{{" }}.app.metadata.name{{ "}}" }} has an error condition on cluster {{ "{{" }} index .app.metadata.labels "REDACTED/name" {{ "}}" }}
          slack:
            attachments: |
              [{
                "title": "{{ "{{" }}.app.metadata.name{{ "}}" }}",
                "title_link": "{{ "{{" }}.context.argocdUrl{{ "}}" }}/applications/{{ "{{" }}.app.metadata.name{{ "}}" }}",
                "color": "#E96D76",
                "fields": [
                  {"title": "Cluster", "value": "{{ "{{" }} index .app.metadata.labels "REDACTED/name" {{ "}}" }}", "short": true},
                  {"title": "Conditions", "value": "{{ "{{" }}range .app.status.conditions{{ "}}" }}{{ "{{" }}.type{{ "}}" }}: {{ "{{" }}.message{{ "}}" }} {{ "{{" }}end{{ "}}" }}", "short": false}
                ]
              }]
        template.app-github-status-syncing: |
          message: "App {{ "{{" }}.app.metadata.name{{ "}}" }} is syncing on cluster {{ .Values.cluster.name }}"
          github:
            repoURLPath: "{{ "{{" }}if .app.spec.source.repoURL{{ "}}" }}{{ "{{" }}.app.spec.source.repoURL{{ "}}" }}{{ "{{" }}else{{ "}}" }}{{ "{{" }}(index .app.spec.sources 0).repoURL{{ "}}" }}{{ "{{" }}end{{ "}}" }}"
            revisionPath: "{{ "{{" }}if .app.status.sync.revision{{ "}}" }}{{ "{{" }}.app.status.sync.revision{{ "}}" }}{{ "{{" }}else{{ "}}" }}{{ "{{" }}index .app.status.sync.revisions 0{{ "}}" }}{{ "{{" }}end{{ "}}" }}"
            status:
              state: pending
              label: "argocd/{{ .Values.cluster.name }}/{{ "{{" }}.app.metadata.name{{ "}}" }}"
              targetURL: "{{ "{{" }}.context.argocdUrl{{ "}}" }}/applications/{{ "{{" }}.app.metadata.name{{ "}}" }}"
        template.app-github-status-pending: |
          message: "App {{ "{{" }}.app.metadata.name{{ "}}" }} is out of sync on cluster {{ .Values.cluster.name }}"
          github:
            repoURLPath: "{{ "{{" }}if .app.spec.source.repoURL{{ "}}" }}{{ "{{" }}.app.spec.source.repoURL{{ "}}" }}{{ "{{" }}else{{ "}}" }}{{ "{{" }}(index .app.spec.sources 0).repoURL{{ "}}" }}{{ "{{" }}end{{ "}}" }}"
            revisionPath: "{{ "{{" }}if .app.status.sync.revision{{ "}}" }}{{ "{{" }}.app.status.sync.revision{{ "}}" }}{{ "{{" }}else{{ "}}" }}{{ "{{" }}index .app.status.sync.revisions 0{{ "}}" }}{{ "{{" }}end{{ "}}" }}"
            status:
              state: pending
              label: "argocd/{{ .Values.cluster.name }}/{{ "{{" }}.app.metadata.name{{ "}}" }}"
              targetURL: "{{ "{{" }}.context.argocdUrl{{ "}}" }}/applications/{{ "{{" }}.app.metadata.name{{ "}}" }}"
        template.app-github-status-success: |
          github:
            repoURLPath: "{{ "{{" }}if .app.spec.source.repoURL{{ "}}" }}{{ "{{" }}.app.spec.source.repoURL{{ "}}" }}{{ "{{" }}else{{ "}}" }}{{ "{{" }}(index .app.spec.sources 0).repoURL{{ "}}" }}{{ "{{" }}end{{ "}}" }}"
            revisionPath: "{{ "{{" }}if .app.status.operationState.syncResult.revision{{ "}}" }}{{ "{{" }}.app.status.operationState.syncResult.revision{{ "}}" }}{{ "{{" }}else{{ "}}" }}{{ "{{" }}index .app.status.operationState.syncResult.revisions 0{{ "}}" }}{{ "{{" }}end{{ "}}" }}"
            status:
              state: success
              label: "argocd/{{ .Values.cluster.name }}/{{ "{{" }}.app.metadata.name{{ "}}" }}"
              targetURL: "{{ "{{" }}.context.argocdUrl{{ "}}" }}/applications/{{ "{{" }}.app.metadata.name{{ "}}" }}"
        template.app-github-status-failure: |
          message: "App {{ "{{" }}.app.metadata.name{{ "}}" }} failed to sync on cluster {{ .Values.cluster.name }}"
          github:
            repoURLPath: "{{ "{{" }}if .app.spec.source.repoURL{{ "}}" }}{{ "{{" }}.app.spec.source.repoURL{{ "}}" }}{{ "{{" }}else{{ "}}" }}{{ "{{" }}(index .app.spec.sources 0).repoURL{{ "}}" }}{{ "{{" }}end{{ "}}" }}"
            revisionPath: "{{ "{{" }}if .app.status.operationState.syncResult.revision{{ "}}" }}{{ "{{" }}.app.status.operationState.syncResult.revision{{ "}}" }}{{ "{{" }}else{{ "}}" }}{{ "{{" }}index .app.status.operationState.syncResult.revisions 0{{ "}}" }}{{ "{{" }}end{{ "}}" }}"
            status:
              state: failure
              label: "argocd/{{ .Values.cluster.name }}/{{ "{{" }}.app.metadata.name{{ "}}" }}"
              targetURL: "{{ "{{" }}.context.argocdUrl{{ "}}" }}/applications/{{ "{{" }}.app.metadata.name{{ "}}" }}"
        template.app-github-status-degraded: |
          message: "App {{ "{{" }}.app.metadata.name{{ "}}" }} is in a degraded state on cluster {{ .Values.cluster.name }}"
          github:
            repoURLPath: "{{ "{{" }}if .app.spec.source.repoURL{{ "}}" }}{{ "{{" }}.app.spec.source.repoURL{{ "}}" }}{{ "{{" }}else{{ "}}" }}{{ "{{" }}(index .app.spec.sources 0).repoURL{{ "}}" }}{{ "{{" }}end{{ "}}" }}"
            revisionPath: "{{ "{{" }}if .app.status.operationState.syncResult.revision{{ "}}" }}{{ "{{" }}.app.status.operationState.syncResult.revision{{ "}}" }}{{ "{{" }}else{{ "}}" }}{{ "{{" }}index .app.status.operationState.syncResult.revisions 0{{ "}}" }}{{ "{{" }}end{{ "}}" }}"
            status:
              state: failure
              label: "argocd/{{ .Values.cluster.name }}/{{ "{{" }}.app.metadata.name{{ "}}" }}"
              targetURL: "{{ "{{" }}.context.argocdUrl{{ "}}" }}/applications/{{ "{{" }}.app.metadata.name{{ "}}" }}"
