defaultDeploy: true

path: apps/argocd
namespace: argocd
releaseName: argocd
syncWave: -30
syncOptions:
  - ServerSideApply=true
ignoreDifferences:
  - group: ""
    kind: Secret
    name: argocd-secret
    jsonPointers:
      - /data
values:
  cluster:
    name: "{{ .Values.cluster.name }}"
  argo-cd:
    crds:
      install: true
    configs:
      cm:
        admin.enabled: "false"
        timeout.reconciliation: "30s"
        url: "https://argocd-server.argocd.{{ .Values.cluster.name }}xxx"
        oidc.config: |
          name: Entra ID
          issuer: $argocd-oidc:issuer
          clientID: $argocd-oidc:clientID
          clientSecret: $argocd-oidc:clientSecret
          requestedScopes:
            - openid
            - profile
            - email
          requestedIDTokenClaims:
            groups:
              essential: true
      rbac:
        scopes: "[groups]"
        policy.default: '{{ if eq .Values.cluster.name "lab" }}role:admin{{ end }}'
        policy.csv: |
          g, 4d4167e8-204c-4328-b5f4-4dae634d46a8, role:admin
          g, 3a65b126-4dbe-4013-88dd-08fb8f45f6f7, role:readonly
          p, 3a65b126-4dbe-4013-88dd-08fb8f45f6f7, applications, delete/*/Pod/*/*, */*, allow
          p, 3a65b126-4dbe-4013-88dd-08fb8f45f6f7, applications, sync, */*, allow
      params:
        application.operations.selfHealTimeout: "5"
    notifications:
      enabled: true
      secret:
        create: false
      argocdUrl: "https://argocd-server.argocd.{{ .Values.cluster.name }}xxx"
      notifiers:
        service.slack: |
          token: $slack-token
        service.github: |
          appID: $github-status-app-id
          installationID: $github-status-app-installation-id
          privateKey: $github-status-app-private-key
      subscriptions:
        - recipients:
            - slack:alerts-infra-plat
          triggers:
            - on-sync-failed
            - on-health-degraded
        - recipients:
            - github
          triggers:
            - on-sync-succeeded
            - on-sync-errored
      triggers:
        trigger.on-sync-failed: |
          - when: app.status.operationState.phase in ['Error', 'Failed']
            send: [app-sync-failed]
        trigger.on-health-degraded: |
          - when: app.status.health.status == 'Degraded'
            send: [app-health-degraded]
        trigger.on-sync-succeeded: |
          - when: app.status.operationState.phase == 'Succeeded'
            send: [app-github-status-success]
            oncePer: app.status.operationState.startedAt
        trigger.on-sync-errored: |
          - when: app.status.operationState.phase in ['Error', 'Failed']
            send: [app-github-status-failure]
            oncePer: app.status.operationState.startedAt
      templates:
        template.app-sync-failed: |
          message: |
            App {{ "{{" }}.app.metadata.name{{ "}}" }} sync {{ "{{" }}.app.status.operationState.phase{{ "}}" }} on {{ "{{" }} index .app.metadata.labels "xxx/name" {{ "}}" }}
          slack:
            attachments: |
              [{
                "title": "{{ "{{" }}.app.metadata.name{{ "}}" }}",
                "title_link": "{{ "{{" }}.context.argocdUrl{{ "}}" }}/applications/{{ "{{" }}.app.metadata.name{{ "}}" }}",
                "color": "#E96D76",
                "fields": [
                  {"title": "Phase", "value": "{{ "{{" }}.app.status.operationState.phase{{ "}}" }}", "short": true},
                  {"title": "Cluster", "value": "{{ "{{" }} index .app.metadata.labels "xxx/name" {{ "}}" }}", "short": true},
                  {"title": "Message", "value": "{{ "{{" }}.app.status.operationState.message{{ "}}" }}", "short": false}
                ]
              }]
        template.app-health-degraded: |
          message: |
            App {{ "{{" }}.app.metadata.name{{ "}}" }} is Degraded on {{ "{{" }} index .app.metadata.labels "xxx/name" {{ "}}" }}
          slack:
            attachments: |
              [{
                "title": "{{ "{{" }}.app.metadata.name{{ "}}" }}",
                "title_link": "{{ "{{" }}.context.argocdUrl{{ "}}" }}/applications/{{ "{{" }}.app.metadata.name{{ "}}" }}",
                "color": "#E96D76",
                "fields": [
                  {"title": "Health", "value": "{{ "{{" }}.app.status.health.status{{ "}}" }}", "short": true},
                  {"title": "Cluster", "value": "{{ "{{" }} index .app.metadata.labels "xxx/name" {{ "}}" }}", "short": true}
                ]
              }]
        template.app-github-status-success: |
          github:
            repoURLPath: "{{ "{{" }}.app.spec.source.repoURL{{ "}}" }}"
            revisionPath: "{{ "{{" }}.app.status.operationState.syncResult.revision{{ "}}" }}"
            status:
              state: success
              label: "argocd/{{ .Values.cluster.name }}/{{ "{{" }}.app.metadata.name{{ "}}" }}"
              targetURL: "{{ "{{" }}.context.argocdUrl{{ "}}" }}/applications/{{ "{{" }}.app.metadata.name{{ "}}" }}"
        template.app-github-status-failure: |
          github:
            repoURLPath: "{{ "{{" }}.app.spec.source.repoURL{{ "}}" }}"
            revisionPath: "{{ "{{" }}.app.status.operationState.syncResult.revision{{ "}}" }}"
            status:
              state: failure
              label: "argocd/{{ .Values.cluster.name }}/{{ "{{" }}.app.metadata.name{{ "}}" }}"
              targetURL: "{{ "{{" }}.context.argocdUrl{{ "}}" }}/applications/{{ "{{" }}.app.metadata.name{{ "}}" }}"
