path: apps/argocd
namespace: argocd
releaseName: argocd
syncWave: -30
syncOptions:
  - ServerSideApply=true
ignoreDifferences:
  - group: ""
    kind: Secret
    name: argocd-secret
    jsonPointers:
      - /data
values:
  argo-cd:
    configs:
      cm:
        url: "https://argocd.{{ .Values.cluster.name }}xxx"
