defaultDeploy: true

path: apps/argocd
namespace: argocd
releaseName: argocd
syncWave: -30
syncOptions:
  - ServerSideApply=true
ignoreDifferences:
  - group: ""
    kind: Secret
    name: argocd-secret
    jsonPointers:
      - /data
values:
  cluster:
    name: "{{ .Values.cluster.name }}"
  argo-cd:
    crds:
      install: true
    configs:
      cm:
        admin.enabled: "false"
        timeout.reconciliation: "30s"
        url: "https://argocd-server.argocd.{{ .Values.cluster.name }}xxx"
        oidc.config: |
          name: Entra ID
          issuer: $op-argocd:issuer
          clientID: $op-argocd:clientID
          clientSecret: $op-argocd:clientSecret
          requestedScopes:
            - openid
            - profile
            - email
          requestedIDTokenClaims:
            groups:
              essential: true
      rbac:
        scopes: "[groups]"
        policy.default: '{{ if eq .Values.cluster.name "lab" }}role:admin{{ end }}'
        policy.csv: |
          g, 4d4167e8-204c-4328-b5f4-4dae634d46a8, role:admin
          g, 3a65b126-4dbe-4013-88dd-08fb8f45f6f7, role:readonly
          p, 3a65b126-4dbe-4013-88dd-08fb8f45f6f7, applications, delete/*/Pod/*/*, */*, allow
      params:
        application.operations.selfHealTimeout: "5"
