apiVersion: v2
name: argocd
description: Helm chart for ArgoCD
version: 0.1.0
dependencies:
  - name: argo-cd
    version: "9.7.0"
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-image-updater
    version: "0.9.6"
    repository: https://argoprojlabs.github.io/argocd-image-updater
